source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'haml'
gem 'sass-rails'
gem 'bourbon'
gem 'uglifier'
gem 'font-awesome-rails'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'passenger'
gem 'omniauth-google-oauth2'
gem 'figaro'
gem 'puma'
gem 'hashids'
# gem 'newrelic_rpm'
# gem 'google-analytics-rails'

group :development, :test do
  gem 'spring'
  gem 'priscilla'
  gem 'byebug'
  gem 'better_errors'
  gem 'coffee-rails-source-maps'
  gem 'foreman'
end

group :test do
  gem 'rspec-rails'
  gem 'rspec-mocks'
  gem 'factory_girl_rails'
  gem 'factory_girl', github: 'nicohvi/factory_girl'
  gem 'database_cleaner'
  gem 'guard'
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
  gem 'simplecov'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
end
