# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714ba3f4a557ca96bec64a64a5deaceecbe22f92d3b91a6bb7aee5fe2fd5c60fd5b5dc807ef28a82e44046e913ed024a322b5c1df9cd341c90e2847804bb7c01

test:
  secret_key_base: 2e0d6c1f1c4a7055c10cc282e62300717b19b7670e1d9995b44ff9b09b319596a39fff887c14dff2ac026ba82a15f59ebe6c5e33ab0f992afc2d3a6b560acc98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
